GET http://localhost:3000/players/
###

GET http://localhost:3000/players/1/
###

PUT http://localhost:3000/players/2/
###

GET http://localhost:3000/matches/18/
###

GET http://locahost:3000/players/1/matches
###

GET http://localhost:3000/matches/3/players
###

GET http://localhost:3000/players/1/playerScores/
